# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160427_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSwitchingPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
