# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_codeswitchingphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroplayergame',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
